#!/bin/sh

#===============================================================================
# Wrapper for whisper-cpp
#===============================================================================

#===============================================================================
# script usage
#===============================================================================

usage () {
[ -z "${1}" ] || echo "! ${1}"
echo "Usage: $(basename "$0") -m model -f input -otxt -osrt -ovtt

if you omit the -m option the default model will be used
${HOME}/.local/share/whisper-models/ggml-small.en.bin"
exit 1
}


#===============================================================================
# error messages
#===============================================================================

WRONG_ARGS_ERR='wrong number of arguments passed to script'
INVALID_OPT_ERR='Invalid option:'
REQ_ARG_ERR='requires an argument'
NOTFILE_ERR='not a file'


#===============================================================================
# check number of arguments passed to script
#===============================================================================

[ $# -gt 0 ] || usage "${WRONG_ARGS_ERR}"


#===============================================================================
# getopts check options passed to script
#===============================================================================

while getopts ':m:f:h' opt
do
  case ${opt} in
     m) model="${OPTARG}"
        [ -f "${model}" ] || usage "${model} ${NOTFILE_ERR}";;
     f) input="${OPTARG}"
        [ -f "${input}" ] || usage "${input} ${NOTFILE_ERR}";;
     h) usage;;
     \?) OPTIND=$((OPTIND - 1)) # Handle passthrough of whisper-cpp options
        break;;
     :) usage "${INVALID_OPT_ERR} ${OPTARG} ${REQ_ARG_ERR}" 1>&2;;
  esac
done
shift $((OPTIND-1))


#===============================================================================
# input name
#===============================================================================

input_nopath="${input##*/}"
input_name="${input_nopath%.*}"


#===============================================================================
# check if default model exists
#===============================================================================

model_default="${HOME}/.local/share/whisper-models/ggml-small.en.bin"
[ -f "${model_default}" ] || usage "${model_default} ${NOTFILE_ERR}"


#===============================================================================
# function
#===============================================================================

transcribe () {
exec whisper-cli -np -m "${model:=${model_default}}" -f "${input}" -of "${input_name}" "${@}"
}


#===============================================================================
# run function
#===============================================================================

transcribe "${@}"
